version: "1.0"
info:
  model: int-scaffold
packages:
- name: KusiTestAWSStage0809Project
  gitServerName: kusi_AWSStage02
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
